# Generated by Django 5.1.4 on 2025-05-14 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facility_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='accesslog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='scan_method',
            field=models.CharField(choices=[('qr', 'QR Code'), ('nfc', 'NFC'), ('manual', 'Manual Entry'), ('admin', 'Admin Override')], default='qr', max_length=20),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user_tier_at_time',
            field=models.CharField(blank=True, choices=[('tier1', 'Tier 1'), ('tier2', 'Tier 2'), ('tier3', 'Tier 3')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['-timestamp'], name='facility_ac_timesta_b01a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['facility'], name='facility_ac_facilit_88603d_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user'], name='facility_ac_user_id_0fd0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['status'], name='facility_ac_status_035aaa_idx'),
        ),
    ]
