# Generated by Django 5.1.4 on 2025-05-24

import uuid
from django.db import migrations, models

def assign_unique_uuids(apps, schema_editor):
    Facility = apps.get_model('facility', 'Facility')
    for facility in Facility.objects.all():
        facility.uuid = uuid.uuid4()
        facility.save()

class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_alter_accesslog_options_accesslog_location_and_more'),
    ]

    operations = [
        # Step 1: Add nullable, non-unique UUID field
        migrations.AddField(
            model_name='facility',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(assign_unique_uuids),
        # Step 3: Enforce uniqueness and non-null
        migrations.AlterField(
            model_name='facility',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
