# Generated by Django 5.1.4 on 2025-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
