# Generated by Django 5.1.4 on 2025-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('system', 'System'), ('security', 'Security Alert')], default='info', max_length=20),
        ),
    ]
