# Generated by Django 5.1.4 on 2025-03-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('fitness_goal', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('exercises', models.JSONField(help_text='List of exercises as JSON')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('intensity_level', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('free', 'Free Workout'), ('trainer_assigned', 'Trainer Assigned')], default='free', max_length=20)),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'is_trainer': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.JSONField(default=dict, help_text='Tracks workout progress')),
                ('started_on', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workoutprogram')),
            ],
        ),
    ]
