# Generated by Django 5.1.4 on 2025-03-17 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('muscle_group', models.CharField(help_text='Targeted muscle group', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='feedback',
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.PositiveIntegerField(default=10)),
                ('rest_time', models.PositiveIntegerField(default=60, help_text='Rest time in seconds')),
                ('duration_per_set', models.PositiveIntegerField(default=30, help_text='Duration per set in seconds')),
                ('notes', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout.workoutprogram')),
            ],
        ),
    ]
