# Generated by Django 5.1.4 on 2025-04-05 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_exercise_remove_workoutprogram_exercises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='requestee',
            field=models.ForeignKey(blank=True, help_text='User who requested this trainer-assigned program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_workout_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
