# Generated by Django 5.1.4 on 2025-04-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workoutprogram_requestee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutprogram',
            name='program_type',
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
