# Generated by Django 5.1.4 on 2025-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('facility', 'Facility'), ('user', 'User'), ('trainer', 'Trainer'), ('general', 'General')], default='default_type', max_length=50),
        ),
    ]
