# Generated by Django 5.1.4 on 2025-05-07 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facility_qr_code'),
        ('reports', '0002_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.facility'),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('facility', 'Facility'), ('user', 'User'), ('trainer', 'Trainer'), ('general', 'General'), ('membership', 'Membership'), ('access_logs', 'Access Logs')], max_length=50),
        ),
    ]
