# Generated by Django 5.1.7 on 2025-05-07 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.AlterUniqueTogether(
            name='userspecificworkoutprogram',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userspecificworkoutprogram',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userspecificworkoutprogram',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='userspecificworkoutprogram',
            name='base_program',
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='program',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout_day',
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workoutprogram',
            options={},
        ),
        migrations.RenameField(
            model_name='workoutprogram',
            old_name='created_by',
            new_name='trainer_id',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='order',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='rest_interval',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='workoutprogram',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_images/'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='muscle_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workoutprogram'),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='fitness_goal',
            field=models.CharField(default='General Fitness', max_length=255),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='intensity_level',
            field=models.CharField(default='Moderate Intensity', max_length=255),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='requestee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workout_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='workouts.workoutprogram')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='UserSpecificWorkoutProgram',
        ),
        migrations.DeleteModel(
            name='WorkoutDay',
        ),
    ]
