# Generated by Django 5.1.7 on 2025-05-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workoutprogram'),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='requestee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutprogram',
            name='trainer_id',
            field=models.IntegerField(),
        ),
    ]
