# Generated by Django 5.1.4 on 2025-03-07 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('mealplan_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField()),
                ('trainer_id', models.IntegerField()),
                ('mealplan_name', models.CharField(max_length=255)),
                ('fitness_goal', models.CharField(max_length=255)),
                ('calorie_intake', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meal_type', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealPlan.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='mealPlan.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_name', models.CharField(max_length=255)),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='mealPlan.mealplan')),
            ],
        ),
    ]
