# Generated by Django 5.1.4 on 2025-03-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='mealplan',
        ),
        migrations.AddField(
            model_name='allergen',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='mealPlan.meal'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='weight_goal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
