# Generated by Django 5.1.4 on 2025-04-04 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlan', '0002_remove_allergen_mealplan_allergen_meal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='requestee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_mealplans', to=settings.AUTH_USER_MODEL),
        ),
    ]
