# Generated by Django 5.1.4 on 2025-04-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlan', '0003_mealplan_requestee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='status',
            field=models.CharField(choices=[('not_created', 'Not Created'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_created', max_length=20),
        ),
    ]
