# Generated by Django 5.1.4 on 2025-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlan', '0004_mealplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='plan_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('general', 'General')], default='personal', max_length=10),
        ),
    ]
