# Generated by Django 5.1.4 on 2025-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlan', '0005_mealplan_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='meals', to='mealPlan.allergen'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='user_allergies',
            field=models.TextField(blank=True, help_text='User-declared allergies', null=True),
        ),
    ]
