# Generated by Django 5.1.4 on 2025-03-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
